apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: quant-platform
  labels:
    app: airflow
    component: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc  # Use EFS for multi-pod access
---
# Fallback to gp2 if EFS not available
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc-fallback
  namespace: quant-platform
  labels:
    app: airflow
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2