apiVersion: v1
kind: Secret
metadata:
  name: quant-secrets
  namespace: quant-platform
type: Opaque
stringData:
  # SECURITY WARNING: These are template values only!
  # In production, these MUST be populated by CI/CD from GitHub repository secrets
  # DO NOT commit real credentials to version control
  postgres-password: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
  pgadmin-password: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
  pgadmin-email: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
  polygon-api-key: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
  airflow-admin-username: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
  airflow-admin-password: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
  airflow-admin-email: "CHANGE_ME_SET_VIA_GITHUB_SECRETS"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quant-config
  namespace: quant-platform
data:
  POSTGRES_USER: "quant_user"
  POSTGRES_DB: "quant_data"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  AIRFLOW__WEBSERVER__WARN_DEPLOYMENT_EXPOSURE: "false"
  AIRFLOW__WEBSERVER__SECRET_KEY: "quant_platform_secret_key_2024" 