# Default configuration for the trading platform

# Backtesting configuration
backtest:
  initial_capital: 100000.0
  commission: 0.001          # 0.1% commission rate
  slippage: 0.0005          # 0.05% slippage
  min_commission: 1.0       # Minimum commission per trade

# Risk management configuration
risk:
  max_position_size: 0.1    # Maximum 10% of portfolio per position
  stop_loss_pct: 0.02       # 2% stop loss
  max_drawdown: 0.15        # Maximum 15% drawdown
  max_leverage: 1.0         # No leverage by default
  position_sizing_method: "fixed_fractional"

# Data configuration
data:
  db_connection: "postgresql://quant_user:quant_password@postgres:5432/quant_data"
  data_frequency: "daily"
  lookback_period: 252      # 1 year of daily data

# Execution configuration
execution:
  broker: "simulation"      # simulation, interactive_brokers, alpaca, etc.
  execution_delay: 0.0      # Execution delay in seconds
  market_impact: 0.0001     # Market impact factor

# Strategy-specific configurations
strategies:
  momentum:
    default_short_window: 10
    default_long_window: 20
    default_ma_type: "sma"
    
  mean_reversion:
    default_lookback: 20
    default_threshold: 2.0
    
  rsi:
    default_period: 14
    default_oversold: 30
    default_overbought: 70

# Feature engineering configuration
features:
  technical_indicators:
    sma_periods: [10, 20, 50, 200]
    ema_periods: [10, 20, 50]
    rsi_periods: [14, 21]
    macd_config:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger_config:
      period: 20
      std_dev: 2.0
    
  cache_features: true
  feature_store_enabled: true

# Logging configuration
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/trading_platform.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance and optimization
performance:
  parallel_processing: false
  max_workers: 4
  chunk_size: 1000
  enable_caching: true

# Visualization configuration
visualization:
  default_chart_style: "plotly"
  save_charts: true
  chart_directory: "charts/"
  
# Monitoring and alerts
monitoring:
  enable_alerts: false
  alert_email: "admin@example.com"
  alert_thresholds:
    max_drawdown: 0.10
    min_sharpe: 0.5
    
# Development settings
development:
  debug_mode: false
  save_intermediate_results: false
  validate_data: true